<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>Egui.Silk.NET</PackageId>
    <Title>Egui.Silk.NET</Title>
    <Description>An easy-to-use immediate mode GUI</Description>
    <Version>0.5.3+0.33.2</Version>
    <Authors>Douglas Dwyer</Authors>
    <RepositoryUrl>https://github.com/DouglasDwyer/Egui.NET</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT OR Apache-2.0</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Egui\Egui.csproj" />
    <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/"/>
  </ItemGroup>
</Project>
