<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Egui\Egui.csproj" />
    <ProjectReference Include="..\..\Egui.Silk.NET.OpenGL\Egui.Silk.NET.OpenGL.csproj" />
  </ItemGroup>

  <ItemGroup>
      <EmbeddedResource Include="Resources\**">
        <LogicalName>$([System.String]::new('%(RelativeDir)').Replace('\','.').Replace('/','.').Substring(10))%(FileName)%(Extension)</LogicalName>
      </EmbeddedResource>
  </ItemGroup>
</Project>
