[workspace]
members = [
    "egui_net",
    "egui_net_bindgen",
    "serde-generate",
    "serde-reflection"
]
default-members = [ "egui_net" ]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]

# Internal dependencies
egui_net = { path = "egui_net" }
egui_net_bindgen = { path = "egui_net_bindgen" }
serde-generate = { path = "serde-generate", default-features = false, features = [ "csharp" ] }
serde-reflection = { path = "serde-reflection", default-features = false }

# External dependencies
bincode = { version = "1.3.3", default-features = false }
convert_case = { version = "0.7.1", default-features = false }
csbindgen = { version = "1.9.3", default-features = false }
egui = { version = "0.31.1", default-features = false, features = [ "serde" ] }
rustdoc-types = { version = "0.35.0", default-features = false }
serde = { version = "1.0.219", default-features = false, features = [ "derive" ] }
serde_json = { version = "1.0.138", default-features = false, features = [ "std" ] }