<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Egui</PackageId>
        <Title>Egui</Title>
        <Description>An easy-to-use immediate mode GUI</Description>
        <Version>0.9.0+0.36.1</Version>
        <Authors>Douglas Dwyer</Authors>
        <RepositoryUrl>https://github.com/DouglasDwyer/Egui.NET</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT OR Apache-2.0</PackageLicenseExpression>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>1591</NoWarn>
        <Nullable>enable</Nullable>

        <IsAotCompatible>true</IsAotCompatible>

        <RuntimeIdentifiers Condition="$([MSBuild]::IsOSPlatform('Windows')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'Arm64'">win-arm64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::IsOSPlatform('Windows')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'x64'">win-x64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::IsOSPlatform('OSX')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'Arm64'">osx-arm64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::IsOSPlatform('OSX')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'x64'">osx-x64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::IsOSPlatform('Linux')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'Arm64'">linux-arm64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::IsOSPlatform('Linux')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'x64'">linux-x64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="'$(Configuration)'=='Release'">win-arm64;win-x64;osx-arm64;osx-x64;linux-arm64;linux-x64</RuntimeIdentifiers>
      </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DouglasDwyer.FixedArray" Version="0.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Egui.SourceGenerators/Egui.SourceGenerators.csproj"
            OutputItemType="Analyzer"
            ReferenceOutputAssembly="false" />
    </ItemGroup>

    <PropertyGroup>
        <CargoExecutable Condition="'$(Configuration)'=='Debug'">cargo</CargoExecutable>
        <CargoExecutable Condition="'$(Configuration)'=='Release'">cross</CargoExecutable>

        <CargoProfile Condition="'$(Configuration)'=='Debug'">dev</CargoProfile>
        <CargoProfile Condition="'$(Configuration)'=='Release'">release</CargoProfile>
        
        <CargoFeatures Condition="'$(Configuration)'=='Debug'"></CargoFeatures>
        <CargoFeatures Condition="'$(Configuration)'=='Release'"></CargoFeatures>

        <CargoUnstableOptions Condition="'$(Configuration)'=='Debug'"></CargoUnstableOptions>
        <CargoUnstableOptions Condition="'$(Configuration)'=='Release'"></CargoUnstableOptions>

        <CargoProfileOutput Condition="'$(Configuration)'=='Debug'">debug</CargoProfileOutput>
        <CargoProfileOutput Condition="'$(Configuration)'=='Release'">release</CargoProfileOutput>

        <CargoVariables Condition="'$(Configuration)'=='Debug'"></CargoVariables>
        <CargoVariables Condition="'$(Configuration)'=='Release'">CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER=rust-lld;CARGO_TARGET_AARCH64_PC_WINDOWS_MSVC_LINKER=rust-lld</CargoVariables>
    </PropertyGroup>

    <Target Name="BuildNativeLibrary" BeforeTargets="CoreCompile">
        <ItemGroup>
            <RIDList Include="$(RuntimeIdentifiers)" />
        </ItemGroup>

        <ItemGroup>
            <CargoBuild Include="$(MSBuildProjectFile)" Condition="'%(RIDList.Identity)' == 'win-arm64'">
                <Properties>CargoTarget=aarch64-pc-windows-msvc</Properties>
            </CargoBuild>
            <CargoBuild Include="$(MSBuildProjectFile)" Condition="'%(RIDList.Identity)' == 'win-x64'">
                <Properties>CargoTarget=x86_64-pc-windows-msvc</Properties>
            </CargoBuild>
            <CargoBuild Include="$(MSBuildProjectFile)" Condition="'%(RIDList.Identity)' == 'osx-arm64'">
                <Properties>CargoTarget=aarch64-apple-darwin</Properties>
            </CargoBuild>
            <CargoBuild Include="$(MSBuildProjectFile)" Condition="'%(RIDList.Identity)' == 'osx-x64'">
                <Properties>CargoTarget=x86_64-apple-darwin</Properties>
            </CargoBuild>
            <CargoBuild Include="$(MSBuildProjectFile)" Condition="'%(RIDList.Identity)' == 'linux-arm64'">
                <Properties>CargoTarget=aarch64-unknown-linux-gnu</Properties>
            </CargoBuild>
            <CargoBuild Include="$(MSBuildProjectFile)" Condition="'%(RIDList.Identity)' == 'linux-x64'">
                <Properties>CargoTarget=x86_64-unknown-linux-gnu</Properties>
            </CargoBuild>
        </ItemGroup>

        <MSBuild Projects="@(CargoBuild)" BuildInParallel="true" StopOnFirstFailure="true" Targets="CargoBuild"/>

        <ItemGroup>
            <Compile Include="../target/bindings/**/*.cs" />
        </ItemGroup>
    </Target>

    <Target Name="CargoBuild">
        <Exec Command="$(CargoExecutable) build --profile $(CargoProfile) --target $(CargoTarget) $(CargoUnstableOptions) $(CargoFeatures)"
            EnvironmentVariables="$(CargoVariables)"
            WorkingDirectory=".." />
    </Target>
    
    <ItemGroup>
        <None Include="../target/aarch64-pc-windows-msvc/$(CargoProfileOutput)/egui_net.dll"
            Condition="$([System.String]::new('$(RuntimeIdentifiers)').Contains('win-arm64'))"
            Pack="true"
            CopyToOutputDirectory="Always"
            PackagePath="runtimes/win-arm64/native/egui_net.dll"
            Link="egui_net.dll"/>
        <None Include="../target/x86_64-pc-windows-msvc/$(CargoProfileOutput)/egui_net.dll"
            Condition="$([System.String]::new('$(RuntimeIdentifiers)').Contains('win-x64'))"
            Pack="true"
            CopyToOutputDirectory="Always"
            PackagePath="runtimes/win-x64/native/egui_net.dll"
            Link="egui_net.dll"/>
        <None Include="../target/aarch64-apple-darwin/$(CargoProfileOutput)/libegui_net.dylib"
            Condition="$([System.String]::new('$(RuntimeIdentifiers)').Contains('osx-arm64'))"
            Pack="true"
            CopyToOutputDirectory="Always"
            PackagePath="runtimes/osx-arm64/native/libegui_net.dylib"
            Link="egui_net.dylib"/>
        <None Include="../target/x86_64-apple-darwin/$(CargoProfileOutput)/libegui_net.dylib"
            Condition="$([System.String]::new('$(RuntimeIdentifiers)').Contains('osx-x64'))"
            Pack="true"
            CopyToOutputDirectory="Always"
            PackagePath="runtimes/osx-x64/native/libegui_net.dylib"
            Link="egui_net.dylib"/>
        <None Include="../target/aarch64-unknown-linux-gnu/$(CargoProfileOutput)/libegui_net.so"
            Condition="$([System.String]::new('$(RuntimeIdentifiers)').Contains('linux-arm64'))"
            Pack="true"
            CopyToOutputDirectory="Always"
            PackagePath="runtimes/linux-arm64/native/libegui_net.so"
            Link="egui_net.so"/>
        <None Include="../target/x86_64-unknown-linux-gnu/$(CargoProfileOutput)/libegui_net.so"
            Condition="$([System.String]::new('$(RuntimeIdentifiers)').Contains('linux-x64'))"
            Pack="true"
            CopyToOutputDirectory="Always"
            PackagePath="runtimes/linux-x64/native/libegui_net.so"
            Link="egui_net.so"/>
        <None Include="../README.md" Pack="true" PackagePath="/"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="../serde-generate/runtime/csharp/Bincode/*.cs" />
        <Compile Include="../serde-generate/runtime/csharp/Serde/*.cs" />
    </ItemGroup>
</Project>
