#![allow(warnings)]

#![feature(fn_traits)]
#![feature(thread_local)]
#![feature(tuple_trait)]
#![feature(unboxed_closures)]

use egui::*;
use egui::color_picker::*;
use egui::ecolor::*;
use egui::emath::*;
use egui::emath::align::*;
use egui::emath::easing::*;
use egui::emath::smart_aim::*;
use egui::epaint::*;
use egui::epaint::tessellator::*;
use egui::epaint::text::*;
use egui::epaint::text::cursor::*;
use egui::epaint::textures::*;
use egui::Id;
use egui::collapsing_header::*;
use egui::containers::*;
use egui::containers::menu::*;
use egui::containers::menu::SubMenu;
use egui::gui_zoom::*;
use egui::introspection::*;
use egui::layers::*;
use egui::load::*;
use egui::os::*;
use egui::output::*;
use egui::panel::*;
use egui::scroll_area::*;
use egui::style::*;
use egui::text::*;
use egui::text_edit::*;
use egui::text_selection::*;
use egui::text_selection::text_cursor_state::*;
use egui::text_selection::visuals::*;
use egui::util::undoer::*;
use egui::widget_style::*;
use egui_extras::*;
use egui_extras::syntax_highlighting::*;
use egui_net_ffi::*;
use bitflags::Flags as _;
use serde::*;
use serde::de::*;
use std::borrow::*;
use std::collections::*;
use std::ffi::*;
use std::marker::PhantomData;
use std::marker::Tuple;
use std::mem::*;
use std::ops::*;
use std::sync::atomic::AtomicUsize;
use std::time::*;
use std::panic;
use std::panic::catch_unwind;
use std::sync::*;

/// The global memory allocator to use.
#[cfg(not(target_arch = "wasm32"))]
#[global_allocator]
static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../target/bindings/egui_fn.rs"));

/// A registry containing all `egui` functions callable from C#.
const EGUI_FNS: EguiFnMap = AUTOGENERATED_EGUI_FNS
    // Bindings for Area
    .with(EguiFn::egui_containers_area_Area_show, |ctx: EguiPointer<Context>, area: Area, callback: EguiCallback| unsafe { area.show(ctx.get(), |ui| callback.invoke(ui as *const _ as *const _)).response })
    // Bindings for AreaState
    .with(EguiFn::egui_containers_area_AreaState_load, |ctx: EguiPointer<Context>, id: Id| unsafe { AreaState::load(ctx.get(), id) })
    // Bindings fot Atoms
    // Returns `(has_text, text)` instead of `Option<String>`: `EguiMarshal.SerializerCache<T>`
    // dispatches purely on the runtime `Type`, and a C# nullable *reference* annotation
    // (`string?`) is erased at runtime (`typeof(string?) == typeof(string)`), so there is no way
    // for it to know an `Option<String>` return needs the extra presence byte read first: it
    // always deserializes as a bare (length-prefixed) string, misreading the wire data.
    .with(EguiFn::egui_atomics_atoms_Atoms_text, |atoms: Atoms| {
        let text = atoms.text();
        (text.is_some(), text.map(|x| x.into_owned()).unwrap_or_default())
    })
    // Bindings for AtomLayoutResponse
    .with(EguiFn::egui_atomics_atom_layout_AtomLayoutResponse_custom_rects, |r: AtomLayoutResponse| r.custom_rects().collect::<Vec<_>>())
    // Bindings for CentralPanel
    .with(EguiFn::egui_containers_panel_CentralPanel_show, |mut ui: EguiPointer<Ui>, panel: CentralPanel, callback: EguiCallback| unsafe {
        panel.show(ui.get_mut(), |ui| {
            callback.invoke(ui as *const _ as *const _);
        }).response
    })
    // Bindings for Checkbox
    .with(EguiFn::egui_widgets_checkbox_Checkbox_ui, |mut ui: EguiPointer<Ui>, atoms: Atoms, mut checked: bool, indeterminate: bool, classes: Classes| unsafe {
        let mut checkbox = Checkbox::new(&mut checked, atoms).indeterminate(indeterminate);
        *checkbox.classes_mut() = classes;
        (ui.get_mut().add(checkbox), checked)
    })
    // Bindings for CollapsingHeader
    .with(EguiFn::egui_containers_collapsing_header_CollapsingHeader_show, |mut ui: EguiPointer<Ui>, obj: CollapsingHeader, callback: EguiCallback| unsafe {
        let result = obj.show(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _));
        (result.header_response, result.body_response, result.openness)
    })
    .with(EguiFn::egui_containers_collapsing_header_CollapsingHeader_show_unindented, |mut ui: EguiPointer<Ui>, obj: CollapsingHeader, callback: EguiCallback| unsafe {
        let result = obj.show_unindented(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _));
        (result.header_response, result.body_response, result.openness)
    })
    // Bindings for CollapsingState
   .with(EguiFn::egui_containers_collapsing_header_CollapsingState_show_body_indented, |mut state: CollapsingState, header_response: Response, mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe {
        (state.show_body_indented(&header_response, ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _)).map(|x| x.response), state)
    })    
   .with(EguiFn::egui_containers_collapsing_header_CollapsingState_show_body_unindented, |mut state: CollapsingState, mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe {
        (state.show_body_unindented(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _)).map(|x| x.response), state)
    })    
   .with(EguiFn::egui_containers_collapsing_header_CollapsingState_show_header, |mut state: CollapsingState, mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe {
        let result = state.show_header(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _));
        (result.toggle_button_response, result.header_response.response, result.state)
    })
    .with(EguiFn::egui_containers_collapsing_header_EguiCollapsingStateShowToggleButtonParams_unpack, |mut x: EguiPointer<EguiCollapsingStateShowToggleButtonParams>| unsafe {
        let params = x.get_mut();
        (params.ui as *const _ as usize, params.openness, params.response.clone())
    })
   .with(EguiFn::egui_containers_collapsing_header_CollapsingState_show_toggle_button, |mut state: CollapsingState, mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe {
        state.show_toggle_button(ui.get_mut(), move |ui, openness, response| {
            let pack = EguiCollapsingStateShowToggleButtonParams {
                ui,
                openness,
                response
            };
            callback.invoke(&pack as *const _ as *const _);
        })
    })
    // Bindings for Color32
    .with(EguiFn::ecolor_color32_Color32_from_hex, |x: String| Color32::from_hex(&x).ok())
    // Bindings for ColorImage
    .with(EguiFn::epaint_image_ColorImage_region_by_pixels, |x: ColorImage, xy: [usize; 2], wh: [usize; 2]| x.region_by_pixels(xy, wh))
    // Bindings for Context
    .with(EguiFn::egui_context_Context_default, || {
        let ctx = Context::default();
        egui_extras::install_image_loaders(&ctx);
        EguiHandle::to_heap(ctx)
    })
    .with(EguiFn::egui_context_Context_ref_id, |ctx: EguiPointer<Context>| unsafe { *transmute::<_, &usize>(ctx.get()) })
    .with(EguiFn::egui_context_Context_ref_decrement, |ctx: EguiPointer<Context>| unsafe { (ctx.get() as *const Context).read(); })
    .with(EguiFn::egui_context_Context_request_discard, |ctx: EguiPointer<Context>, x: String| unsafe { ctx.get().request_discard(x) })
    //.with(EguiFn::egui_context_Context_add_bytes_loader, |ctx: EguiPointer<Context>, name: String, id: usize, loader_index: usize, implementation: EguiPointer<EguiBytesLoaderImpl>| unsafe { ctx.get().add_bytes_loader(Arc::new(EguiWrappedBytesLoader { id, loader_index, name, implementation: *implementation.get() })); })
    .with(EguiFn::egui_context_Context_layer_painter, |ctx: EguiPointer<Context>, layer_id: LayerId| unsafe { EguiHandle::to_heap(ctx.get().layer_painter(layer_id)) })
    .with(EguiFn::egui_context_Context_debug_painter, |ctx: EguiPointer<Context>| unsafe { EguiHandle::to_heap(ctx.get().debug_painter()) })
    .with(EguiFn::egui_context_Context_input, |ctx: EguiPointer<Context>| unsafe { ctx.get().input(|i| i.clone()) })
    .with(EguiFn::egui_context_Context_input_mut, |ctx: EguiPointer<Context>, state: InputState| unsafe { ctx.get().input_mut(|i| *i = state) })
    .with(EguiFn::egui_context_Context_tessellation_options, |ctx: EguiPointer<Context>| unsafe { ctx.get().tessellation_options(|i| i.clone()) })
    .with(EguiFn::egui_context_Context_tessellation_options_mut, |ctx: EguiPointer<Context>, opts: TessellationOptions| unsafe { ctx.get().tessellation_options_mut(|i| *i = opts) })
    .with(EguiFn::egui_context_Context_graphics, |ctx: EguiPointer<Context>| unsafe { ctx.get().graphics(|i| i.clone()) })
    .with(EguiFn::egui_context_Context_graphics_mut, |ctx: EguiPointer<Context>, state: GraphicLayers| unsafe { ctx.get().graphics_mut(|i| *i = state) })
    .with(EguiFn::egui_context_Context_input_for, |ctx: EguiPointer<Context>, id: ViewportId| unsafe { ctx.get().input_for(id, |i| i.clone()) })
    .with(EguiFn::egui_context_Context_input_mut_for, |ctx: EguiPointer<Context>, id: ViewportId, state: InputState| unsafe { ctx.get().input_mut_for(id, |i| *i = state) })
    .with(EguiFn::egui_context_Context_output, |ctx: EguiPointer<Context>| unsafe { ctx.get().output(|i| i.clone()) })
    .with(EguiFn::egui_context_Context_output_mut, |ctx: EguiPointer<Context>, state: PlatformOutput| unsafe { ctx.get().output_mut(|i| *i = state) })
    .with(EguiFn::egui_context_Context_load_texture, |ctx: EguiPointer<Context>, name: String, image: ImageData, options: TextureOptions| unsafe { EguiHandle::to_heap(ctx.get().load_texture(name, image, options)) })
    .with(EguiFn::egui_context_Context_memory, |ctx: EguiPointer<Context>, callback: EguiCallback| unsafe { ctx.get().memory(|i| {
        let mut cloned = i.clone();
        callback.invoke(&mut cloned as *const _ as *const _);
    }) })
    .with(EguiFn::egui_context_Context_memory_mut, |ctx: EguiPointer<Context>, callback: EguiCallback| unsafe { ctx.get().memory_mut(|i| callback.invoke(i as *const _ as *const _)) })
    .with(EguiFn::egui_context_Context_run_ui, |ctx: EguiPointer<Context>, raw_input: RawInput, callback: EguiCallback| unsafe {
        ctx.get().run_ui(raw_input, |ui| {
            callback.invoke(ui as *const _ as *const _);
        })
    })
    .with(EguiFn::egui_context_Context_run_ffi, |ctx: EguiPointer<Context>, mut input: EguiPointer<EguiFfi>, callback: EguiCallback| unsafe {
        let raw_input = input.get().raw_input();

        let mut full_output = ctx.get().run_ui(raw_input, |ui| {
            callback.invoke(ui as *const _ as *const _);
        });

        let primitives = ctx.get().tessellate(take(&mut full_output.shapes), full_output.pixels_per_point);
        let meshes = primitives.into_iter().filter_map(|x| if let Primitive::Mesh(mesh) = x.primitive {
            Some((x.clip_rect, mesh))
        }
        else {
            None
        });
        input.get_mut().set_full_output(full_output);
        input.get_mut().set_meshes(meshes);
    })
    .with(EguiFn::egui_context_Context_fonts_mut, |ctx: EguiPointer<Context>, callback: EguiCallback| unsafe {
        ctx.get().fonts_mut(|fonts| callback.invoke(fonts as *mut _ as *const _))
    })
    .with(EguiFn::egui_context_Context_register_widget_info, |ctx: EguiPointer<Context>, id: Id, info: WidgetInfo| unsafe { ctx.get().register_widget_info(id, || info.clone()) })
    // Bindings for ComboBox
    .with(EguiFn::egui_containers_combo_box_ComboBox_show_ui, |mut ui: EguiPointer<Ui>, obj: ComboBox, callback: EguiCallback| unsafe { obj.show_ui(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _)).response })
    // Bindings for DatePickerButton
    .with(EguiFn::egui_extras_datepicker_button_DatePickerButton_ui, |mut ui: EguiPointer<Ui>, obj: SerializableDatePickerButton, mut date: (i16, i8, i8)| unsafe {
        let mut selection = jiff::civil::Date::new(date.0, date.1, date.2).expect("Invalid date");
        let mut button = DatePickerButton::new(&mut selection)
            .combo_boxes(obj.combo_boxes)
            .arrows(obj.arrows)
            .calendar(obj.calendar)
            .calendar_week(obj.calendar_week)
            .show_icon(obj.show_icon)
            .format(obj.format)
            .highlight_weekends(obj.highlight_weekends)
            .reverse_years(obj.reverse_years);

        if let Some(id_salt) = obj.id_salt.as_deref() {
            button = button.id_salt(id_salt);
        }
        if let Some((start, end)) = obj.start_end_years {
            button = button.start_end_years(start..=end);
        }
        if let Some(year) = obj.year_scroll_to {
            button = button.year_scroll_to(year);
        }

        let response = ui.get_mut().add(button);
        (response, (selection.year(), selection.month(), selection.day()))
    })
    // Bindings for DragValue
    .with(EguiFn::egui_widgets_drag_value_DragValue_ui, |mut ui: EguiPointer<Ui>, obj: SerializableDragValue, mut value: f64| unsafe {
        (ui.get_mut().add(obj.to_drag_value(&mut value)), value)
    })
    .with(EguiFn::egui_widgets_drag_value_DragValue_atoms, |obj: SerializableDragValue| {
        let mut dummy_value = 0.0;
        obj.to_drag_value(&mut dummy_value).atoms().clone()
    })
    // Bindings for ecolor
    .with(EguiFn::ecolor_hsva_hsv_from_rgb, |rgb: [f32; 3]| hsv_from_rgb(rgb))
    .with(EguiFn::ecolor_hsva_rgb_from_hsv, |hsv: (f32, f32, f32)| rgb_from_hsv(hsv))
    // Bindings for EguiFfi
    .with(EguiFn::egui_EguiFfi_new, || EguiHandle::to_heap(EguiFfi::default()))
    // Bindings for epaint
    .with(EguiFn::epaint_shape_transform_adjust_colors, |mut shape: Shape, callback: EguiCallback| unsafe {
        shape_transform::adjust_colors(&mut shape, move |color| callback.invoke(color as *const _ as *const _));
        shape
    })
    .with(EguiFn::epaint_text_fonts_FontDefinitions_builtin_font_names, || FontDefinitions::builtin_font_names().into_iter().map(ToString::to_string).collect::<Vec<_>>())
    // `fast_midpoint` is trivial arithmetic (`(a + b) / 2`), reimplemented directly in C# as
    // `EmathHelpers.FastMidpoint` (matching how `Lerp`/`Remap`/etc. are already handled) rather
    // than bound here, so it works generically for both `float` and `double`.
    // `FontData::variation_axes` is auto-bound now that `FontVariationAxis` derives serde
    // (added in egui-rs/crates/epaint/src/text/fonts.rs); no manual binding needed.
    // `ByteIndex`/`CharIndex` are `#[serde(transparent)]` newtypes, which used to make them
    // invisible to the autobinder (indistinguishable from a bare `usize`) - fixed generically in
    // `egui_net_bindgen::BindingsGenerator::inject_tuple_struct_wrappers`, which synthesizes a
    // registry entry straight from rustdoc for any tuple struct the tracer doesn't see on its
    // own. That's why `Row::char_at`/`char_count_excluding_newline`/`x_offset`,
    // `PlacedRow::char_count_including_newline`, `LayoutJob::format_at_byte`, `CCursor::new`, and
    // `text_cursor_state::byte_index_from_char_index`/`char_index_from_byte_index` are all
    // auto-bound now with no code here.
    //
    // `ByteRange`/`CharRange` (= `Range<ByteIndex>`/`Range<CharIndex>`) are a separate story:
    // `std::ops::Range<T>`'s `Serialize` impl uses the fixed name "Range" for every `T`, so the
    // tracer conflates it with any *other* `Range<T>` reachable from a bound type (e.g.
    // `RowVisuals::glyph_vertex_range: Range<usize>`) - as soon as the two disagree on their
    // element format, tracing panics with an `Incompatible` error. Bound concretely instead,
    // same as `text_cursor_state::slice_char_range` (which takes `Range<CharIndex>` directly and
    // was already hand-bound before this).
    .with(EguiFn::epaint_text_index_ByteRange_full, |text: String| { let r = ByteRange::full(&text); (r.start, r.end) })
    .with(EguiFn::epaint_text_index_ByteRange_slice, |text: String, start: ByteIndex, end: ByteIndex| (start..end).slice(&text).to_string())
    .with(EguiFn::epaint_text_index_CharRange_full, |text: String| { let r = CharRange::full(&text); (r.start, r.end) })
    .with(EguiFn::egui_text_selection_text_cursor_state_slice_char_range, |s: String, start: CharIndex, end: CharIndex| slice_char_range(&s, start..end).to_string())
    // `VariationCoords::new` takes `impl IntoIterator<Item = (T, f32)>` for a method type
    // parameter `T: IntoTag`, which the autobinder doesn't unwrap (it only recognizes `impl
    // IntoTag` written directly in a signature, not behind another generic); bound concretely
    // against `Vec<(Tag, f32)>` instead, since `Tag: IntoTag` (the identity case).
    .with(EguiFn::epaint_text_text_layout_types_VariationCoords_new, |values: Vec<(Tag, f32)>| VariationCoords::new(values))
    // `TextureAtlas` itself is never exposed to C# (it's purely internal - see `IGNORE_FNS`) and
    // has no wire representation, so `TextureAtlas::options` can't take a `TextureAtlas` argument
    // directly. `FontsView` (already exposed as a pointer type) exposes the exact same data
    // through `FontsView::options`, which just forwards to `FontsImpl::options` and then
    // `TextureAtlas::options` - so this reuses that path instead of inventing a new one.
    .with(EguiFn::epaint_texture_atlas_TextureAtlas_options, |fonts: EguiPointer<FontsView>| unsafe { fonts.get().options().clone() })
    // Bindings for Frame
    .with(EguiFn::egui_containers_frame_Frame_show, |mut ui: EguiPointer<Ui>, frame: Frame, callback: EguiCallback| unsafe { frame.show(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _)).response })
    // Bindings for FrameDurations
    .with(EguiFn::egui_widgets_image_FrameDurations_all, |x: FrameDurations| x.all().copied().collect::<Vec<_>>())
    // Bindings for GraphicLayers
    .with(EguiFn::egui_layers_GraphicLayers_drain, |mut x: GraphicLayers, area_order: Vec<LayerId>, to_global: ahash::HashMap<LayerId, TSTransform>| (x.drain(&area_order, &to_global), x))
    .with(EguiFn::egui_layers_GraphicLayers_get, |mut x: GraphicLayers, layer_id: LayerId| x.get(layer_id).cloned())
    // Bindings for Grid
    .with(EguiFn::egui_grid_Grid_show, |mut ui: EguiPointer<Ui>, grid: Grid, callback: EguiCallback| unsafe {
        grid.show(ui.get_mut(), |ui| {
            callback.invoke(ui as *const _ as *const _);
        }).response
    })
    // Bindings for HexColor
    .with(EguiFn::ecolor_hex_color_runtime_HexColor_from_str, |x: String| <HexColor as std::str::FromStr>::from_str(&x).ok())
    .with(EguiFn::ecolor_hex_color_runtime_HexColor_from_str_without_hash, |x: String| HexColor::from_str_without_hash(&x).ok())
    // Bindings for Hsva
    .with(EguiFn::ecolor_hsva_Hsva_from_additive_srgb, |x: [u8; 3]| Hsva::from_additive_srgb(x))
    .with(EguiFn::ecolor_hsva_Hsva_from_srgb, |x: [u8; 3]| Hsva::from_srgb(x))
    .with(EguiFn::ecolor_hsva_Hsva_from_srgba_premultiplied, |x: [u8; 4]| Hsva::from_srgba_premultiplied(x))
    .with(EguiFn::ecolor_hsva_Hsva_from_srgba_unmultiplied, |x: [u8; 4]| Hsva::from_srgba_unmultiplied(x))
    // Bindings for Id
    .with(EguiFn::egui_id_Id_new, |source: String| Id::new(source))
    .with(EguiFn::egui_id_Id_with, |this: Id, child: String| this.with(child))
    // Bindings for KeyboardShortcut
     .with(EguiFn::egui_data_input_keyboard_shortcut_KeyboardShortcut_format, |obj: KeyboardShortcut, is_short: bool, names: [String; 6], is_mac: bool| obj.format(&ModifierNames {
        is_short,
        alt: names[0].as_str(),
        ctrl: names[1].as_str(),
        shift: names[2].as_str(),
        mac_alt: names[3].as_str(),
        mac_cmd: names[4].as_str(),
        concat: names[5].as_str(),
    }, is_mac))
    // Bindings for Memory
    .with(EguiFn::egui_memory_Memory_options, |m: EguiPointer<Memory>| unsafe { m.get().options.clone() })
    .with(EguiFn::egui_memory_Memory_set_options, |mut m: EguiPointer<Memory>, opts: Options| unsafe { m.get_mut().options = opts; })
    .with(EguiFn::egui_memory_Memory_layer_ids, |m: EguiPointer<Memory>| unsafe { m.get().layer_ids().collect::<Vec<_>>() })
    // `Memory::move_focus` is auto-bound now that `FocusDirection` derives serde (added in
    // egui-rs/crates/egui/src/memory/mod.rs); no manual binding needed.
    // Bindings for MenuBar
    .with(EguiFn::egui_containers_menu_MenuBar_ui, |mut ui: EguiPointer<Ui>, obj: MenuBar, callback: EguiCallback| unsafe {
        obj.ui(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _)).response
    })
    // Bindings for MenuButton
    .with(EguiFn::egui_containers_menu_MenuButton_ui, |mut ui: EguiPointer<Ui>, obj: MenuButton, callback: EguiCallback| unsafe {
        let (response, maybe_response) = obj.ui(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _));
        (response, maybe_response.map(|x| x.response))
    })
    // Bindings for SubMenuButton
    .with(EguiFn::egui_containers_menu_SubMenuButton_ui, |mut ui: EguiPointer<Ui>, obj: SubMenuButton, callback: EguiCallback| unsafe {
        let (response, maybe_response) = obj.ui(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _));
        (response, maybe_response.map(|x| x.response))
    })
    // Bindings for Modal
    .with(EguiFn::egui_containers_modal_Modal_show, |ctx: EguiPointer<Context>, obj: Modal, callback: EguiCallback| unsafe {
        let result = obj.show(ctx.get(), |ui| {
            callback.invoke(ui as *const _ as *const _);
        });

        (result.response, result.backdrop_response, result.is_top_modal, result.any_popup_open)
    })
    // Bindings for ModalResponse
    .with(EguiFn::egui_containers_modal_ModalResponse_should_close, |response: Response, backdrop_response: Response, is_top_modal: bool, any_popup_open: bool| ModalResponse {
        response,
        backdrop_response,
        inner: (),
        is_top_modal,
        any_popup_open
    }.should_close())
    // Bindings for ModiferNames
    .with(EguiFn::egui_data_input_modifier_names_ModifierNames_format, |is_short: bool, names: [String; 6], modifiers: Modifiers, is_mac: bool| ModifierNames {
        is_short,
        alt: names[0].as_str(),
        ctrl: names[1].as_str(),
        shift: names[2].as_str(),
        mac_alt: names[3].as_str(),
        mac_cmd: names[4].as_str(),
        concat: names[5].as_str(),
    }.format(&modifiers, is_mac))
    // Bindings for Painter
    .with(EguiFn::egui_painter_Painter_new, |ctx: EguiPointer<Context>, layer_id: LayerId, clip_rect: Rect| unsafe { EguiHandle::to_heap(Painter::new(ctx.get().clone(), layer_id, clip_rect)) })
    .with(EguiFn::egui_painter_Painter_with_layer_id, |painter: EguiPointer<Painter>, layer_id: LayerId| unsafe { EguiHandle::to_heap(painter.get().clone().with_layer_id(layer_id)) })
    .with(EguiFn::egui_painter_Painter_with_clip_rect, |painter: EguiPointer<Painter>, clip_rect: Rect| unsafe { EguiHandle::to_heap(painter.get().clone().with_clip_rect(clip_rect)) })
    .with(EguiFn::egui_painter_Painter_add, |painter: EguiPointer<Painter>, shape: Shape| unsafe { painter.get().add(shape) })
    .with(EguiFn::egui_painter_Painter_for_each_shape, |painter: EguiPointer<Painter>| unsafe {
        let mut shapes = Vec::new();
        painter.get().for_each_shape(|x| shapes.push(x.clone()));
        shapes
    })
    // Bindings for Popup
    .with(EguiFn::egui_containers_popup_Popup_close_all, |ctx: EguiPointer<Context>| unsafe { Popup::close_all(ctx.get()) })
    .with(EguiFn::egui_containers_popup_Popup_close_id, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::close_id(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_open_id, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::open_id(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_toggle_id, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::toggle_id(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_is_any_open, |ctx: EguiPointer<Context>| unsafe { Popup::is_any_open(ctx.get()) })
    .with(EguiFn::egui_containers_popup_Popup_is_id_open, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::is_id_open(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_position_of_id, |ctx: EguiPointer<Context>, id: Id| unsafe { Popup::position_of_id(ctx.get(), id) })
    .with(EguiFn::egui_containers_popup_Popup_show, |ctx: EguiPointer<Context>, popup: SerializablePopup, mut is_open: bool, callback: EguiCallback| unsafe {
        let response = popup.to_popup(ctx.get(), &mut is_open).show(|ui| callback.invoke(ui as *const _ as *const _));
        (response.map(|x| x.response), is_open)
    })
    // `RichText::variation` is auto-bound now that `impl IntoTag` maps to `Tag` (see
    // `bound_ty_name`'s `IntoTag` case in egui_net_bindgen). `variations` (plural) still isn't:
    // its `impl IntoTag` is a step removed, behind a method type parameter
    // (`fn variations<T: IntoTag>(&mut self, values: impl IntoIterator<Item = (T, f32)>)`), which
    // `bound_ty_name` doesn't unwrap.
    // Bindings for RawInput
    .with(EguiFn::egui_data_input_raw_input_RawInput_append, |mut this: RawInput, newer: RawInput| {
        this.append(newer);
        this
    })
    .with(EguiFn::egui_data_input_raw_input_RawInput_take, |mut this: RawInput| {
        let new = this.take();
        (this, new)
    })
    .with(EguiFn::egui_data_input_raw_input_RawInput_viewport, |this: RawInput| this.viewport().clone())
    // Bindings for Rect
    .with(EguiFn::emath_rect_Rect_center, |r: Rect| r.center())
    .with(EguiFn::emath_rect_Rect_set_center, |mut r: Rect, p: Pos2| { r.set_center(p); r })
    .with(EguiFn::emath_rect_Rect_extend_with, |mut r: Rect, p: Pos2| { r.extend_with(p); r })
    .with(EguiFn::emath_rect_Rect_extend_with, |mut r: Rect, p: Pos2| { r.extend_with(p); r })
    .with(EguiFn::emath_rect_Rect_extend_with_x, |mut r: Rect, p: f32| { r.extend_with_x(p); r })
    .with(EguiFn::emath_rect_Rect_extend_with_y, |mut r: Rect, p: f32| { r.extend_with_y(p); r })
    // Bindings for RectAlign
    .with(EguiFn::emath_rect_align_RectAlign_find_best_align, |values_to_try: Vec<RectAlign>, screen_rect: Rect, parent_rect: Rect, gap: f32, expected_size: Vec2| RectAlign::find_best_align(values_to_try.into_iter(), screen_rect, parent_rect, gap, expected_size))
    // Bindings for Resize
    .with(EguiFn::egui_containers_resize_Resize_show, |mut ui: EguiPointer<Ui>, obj: Resize, callback: EguiCallback| unsafe { obj.show(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _)) })
    // Bindings for Response
    .with(EguiFn::egui_response_Response_mark_changed, |mut x: Response| { x.mark_changed(); x })
    .with(EguiFn::egui_response_Response_mark_changed, |mut x: Response| { x.set_close(); x })
    .with(EguiFn::egui_response_Response_widget_info, |x: Response, info: WidgetInfo| x.widget_info(|| info.clone()))
    // Bindings for Scene
    .with(EguiFn::egui_containers_scene_Scene_show, |mut ui: EguiPointer<Ui>, scene: Scene, mut scene_rect: Rect, callback: EguiCallback| unsafe { (scene.show(ui.get_mut(), &mut scene_rect, |ui| callback.invoke(ui as *const _ as *const _)).response, scene_rect) })
    // Bindings for ScrollArea
    .with(EguiFn::egui_containers_scroll_area_ScrollArea_show, |mut ui: EguiPointer<Ui>, obj: ScrollArea, callback: EguiCallback| unsafe {
        let result = obj.show(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _));
        (result.id, result.state, result.content_size, result.inner_rect)
    })
    .with(EguiFn::egui_containers_scroll_area_ScrollArea_show_rows, |mut ui: EguiPointer<Ui>, area: ScrollArea, row_height_sans_spacing: f32, total_rows: usize, callback: EguiCallback| unsafe {
        let result = area.show_rows(ui.get_mut(), row_height_sans_spacing, total_rows,
            |ui, rows| callback.invoke(&EguiScrollAreaShowRowsParams { ui: ui as *const _ as usize, start: rows.start, end: rows.end } as *const _ as *const _));
        (result.id, result.state, result.content_size, result.inner_rect)
    })
    .with(EguiFn::egui_containers_scroll_area_ScrollArea_show_viewport, |mut ui: EguiPointer<Ui>, area: ScrollArea, callback: EguiCallback| unsafe {
        let result = area.show_viewport(ui.get_mut(),
            |ui, rect| callback.invoke(&EguiScrollAreaShowViewportParams { ui: ui as *const _ as usize, min_x: rect.min.x, min_y: rect.min.y, max_x: rect.max.x, max_y: rect.max.y } as *const _ as *const _));
        (result.id, result.state, result.content_size, result.inner_rect)
    })
    // Bindings for Sense
    .with(EguiFn::egui_sense_Sense_interactive, |x: u8| Sense::from_bits_truncate(x).interactive())
    .with(EguiFn::egui_sense_Sense_senses_click, |x: u8| Sense::from_bits_truncate(x).senses_click())
    .with(EguiFn::egui_sense_Sense_senses_drag, |x: u8| Sense::from_bits_truncate(x).senses_drag())
    .with(EguiFn::egui_sense_Sense_is_focusable, |x: u8| Sense::from_bits_truncate(x).is_focusable())
    // Bindings for Shape
    // `gradient_rect` takes a destructuring array pattern (`[from, to]: [Color32; 2]`) as a
    // parameter, which the autobinder can't turn into a valid wrapper closure parameter name;
    // bound by hand against two separate `Color32` parameters instead.
    .with(EguiFn::epaint_shapes_shape_Shape_gradient_rect, |rect: Rect, direction: Direction, from: Color32, to: Color32| Shape::gradient_rect(rect, direction, [from, to]))
    // Bindings for Panel
    .with(EguiFn::egui_containers_panel_Panel_show, |mut ui: EguiPointer<Ui>, panel: Panel, callback: EguiCallback| unsafe { panel.show(ui.get_mut(), |ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_containers_panel_Panel_show_collapsible, |mut ui: EguiPointer<Ui>, mut is_expanded: bool, panel: Panel, callback: EguiCallback| unsafe {
        let response = panel.show_collapsible(ui.get_mut(), &mut is_expanded, |ui| callback.invoke(ui as *const _ as *const _));
        (response.map(|x| x.response), is_expanded)
    })
    .with(EguiFn::egui_containers_panel_Panel_show_switched, |mut ui: EguiPointer<Ui>, mut is_expanded: bool, collapsed_panel: Panel, expanded_panel: Panel, callback: EguiCallback| unsafe {
        let response = Panel::show_switched(ui.get_mut(), &mut is_expanded, collapsed_panel, expanded_panel, |ui, expanded| {
            let pack = EguiSwitchedUi { ui: ui as *const _ as usize, expanded };
            callback.invoke(&pack as *const _ as *const _);
        });
        (response.response, is_expanded)
    })
    // Bindings for Sides
    .with(EguiFn::egui_containers_sides_Sides_show, |mut ui: EguiPointer<Ui>, obj: Sides, l_callback: EguiCallback, r_callback: EguiCallback| unsafe { obj.show(ui.get_mut(), |ui| l_callback.invoke(ui as *const _ as *const _), |ui| r_callback.invoke(ui as *const _ as *const _)) })
    // Bindings for Slider
    .with(EguiFn::egui_widgets_slider_Slider_ui, |mut ui: EguiPointer<Ui>, obj: SerializableSlider, mut value: f64| unsafe {
        (ui.get_mut().add(obj.to_slider(&mut value)), value)
    })
    // Bindings for Strip
    .with(EguiFn::egui_extras_strip_StripBuilder_horizontal, |mut ui: EguiPointer<Ui>, cfg: SerializableStripBuilder, callback: EguiCallback| unsafe {
        let mut builder = StripBuilder::new(ui.get_mut())
            .clip(cfg.clip)
            .sense(cfg.sense);
        if let Some(cell_layout) = cfg.cell_layout {
            builder = builder.cell_layout(cell_layout);
        }
        for size in &cfg.sizes {
            builder = builder.size(*size);
        }
        builder.horizontal(|mut strip| {
            callback.invoke(&mut strip as *mut Strip as *const _);
        })
    })
    .with(EguiFn::egui_extras_strip_StripBuilder_vertical, |mut ui: EguiPointer<Ui>, cfg: SerializableStripBuilder, callback: EguiCallback| unsafe {
        let mut builder = StripBuilder::new(ui.get_mut())
            .clip(cfg.clip)
            .sense(cfg.sense);
        if let Some(cell_layout) = cfg.cell_layout {
            builder = builder.cell_layout(cell_layout);
        }
        for size in &cfg.sizes {
            builder = builder.size(*size);
        }
        builder.vertical(|mut strip| {
            callback.invoke(&mut strip as *mut Strip as *const _);
        })
    })
    .with(EguiFn::egui_extras_strip_Strip_cell, |mut strip: EguiPointer<Strip<'_, '_>>, callback: EguiCallback| unsafe {
        strip.get_mut().cell(|ui| {
            callback.invoke(ui as *const _ as *const _);
        });
    })
    // Bindings for Style
    // `default_text_styles` returns a `BTreeMap`, which the autobinder can't handle generically;
    // bound concretely by collecting it into a `Vec` of pairs instead.
    .with(EguiFn::egui_style_default_text_styles, || default_text_styles().into_iter().collect::<Vec<_>>())
    // Bindings for SubMenu
    .with(EguiFn::egui_containers_menu_SubMenu_show, |mut ui: EguiPointer<Ui>, sub_menu: SubMenu, button_response: Response, content: EguiCallback| unsafe { sub_menu.show(ui.get_mut(), &button_response, |ui| content.invoke(ui as *const _ as *const _)).map(|x| x.response) })
    // Bindings for Table
    .with(EguiFn::egui_extras_table_TableBuilder_show, |mut ui: EguiPointer<Ui>, cfg: SerializableTableBuilder, header_height: Option<f32>, header_callback: Option<EguiCallback>, body_callback: EguiCallback| unsafe {
        let mut builder = TableBuilder::new(ui.get_mut())
            .resizable(cfg.resizable)
            .sense(cfg.sense)
            .vscroll(cfg.vscroll)
            .drag_to_scroll(cfg.drag_to_scroll)
            .stick_to_bottom(cfg.stick_to_bottom)
            .min_scrolled_height(cfg.min_scrolled_height)
            .max_scroll_height(cfg.max_scroll_height)
            .auto_shrink(cfg.auto_shrink)
            .scroll_bar_visibility(cfg.scroll_bar_visibility)
            .animate_scrolling(cfg.animate_scrolling);

        if let Some(striped) = cfg.striped {
            builder = builder.striped(striped);
        }
        if let Some(cell_layout) = cfg.cell_layout {
            builder = builder.cell_layout(cell_layout);
        }
        if let Some(id_salt) = cfg.id_salt.as_deref() {
            builder = builder.id_salt(id_salt);
        }
        if let Some((row, align)) = cfg.scroll_to_row {
            builder = builder.scroll_to_row(row, align);
        }
        if let Some(offset) = cfg.vertical_scroll_offset {
            builder = builder.vertical_scroll_offset(offset);
        }

        for column in &cfg.columns {
            builder = builder.column(*column);
        }

        let result = if let (Some(height), Some(header_cb)) = (header_height, header_callback) {
            let table = builder.header(height, |mut row| {
                header_cb.invoke(&mut row as *mut TableRow as *const _);
            });
            table.body(|body| {
                let mut body = Some(body);
                body_callback.invoke(&mut body as *mut Option<TableBody> as *const _);
            })
        }
        else {
            builder.body(|body| {
                let mut body = Some(body);
                body_callback.invoke(&mut body as *mut Option<TableBody> as *const _);
            })
        };

        (result.id, result.state, result.content_size, result.inner_rect)
    })
    .with(EguiFn::egui_extras_table_TableBody_row, |mut body: EguiPointer<Option<TableBody<'_>>>, height: f32, callback: EguiCallback| unsafe {
        let body = body.get_mut().as_mut().expect("TableBody was already consumed by Rows/HeterogeneousRows");
        body.row(height, |mut row| {
            callback.invoke(&mut row as *mut TableRow as *const _);
        });
    })
    .with(EguiFn::egui_extras_table_TableBody_rows, |mut body: EguiPointer<Option<TableBody<'_>>>, row_height: f32, total_rows: usize, callback: EguiCallback| unsafe {
        let body = body.get_mut().take().expect("TableBody was already consumed by Rows/HeterogeneousRows");
        body.rows(row_height, total_rows, |mut row| {
            callback.invoke(&mut row as *mut TableRow as *const _);
        });
    })
    .with(EguiFn::egui_extras_table_TableBody_heterogeneous_rows, |mut body: EguiPointer<Option<TableBody<'_>>>, heights: Vec<f32>, callback: EguiCallback| unsafe {
        let body = body.get_mut().take().expect("TableBody was already consumed by Rows/HeterogeneousRows");
        body.heterogeneous_rows(heights.into_iter(), |mut row| {
            callback.invoke(&mut row as *mut TableRow as *const _);
        });
    })
    .with(EguiFn::egui_extras_table_TableBody_max_rect, |body: EguiPointer<Option<TableBody<'_>>>| unsafe {
        body.get().as_ref().expect("TableBody was already consumed by Rows/HeterogeneousRows").max_rect()
    })
    .with(EguiFn::egui_extras_table_TableBody_widths, |body: EguiPointer<Option<TableBody<'_>>>| unsafe {
        body.get().as_ref().expect("TableBody was already consumed by Rows/HeterogeneousRows").widths().to_vec()
    })
    .with(EguiFn::egui_extras_table_TableBody_ui_mut, |mut body: EguiPointer<Option<TableBody<'_>>>, callback: EguiCallback| unsafe {
        let body = body.get_mut().as_mut().expect("TableBody was already consumed by Rows/HeterogeneousRows");
        let ui = body.ui_mut();
        callback.invoke(ui as *mut Ui as *const _);
    })
    .with(EguiFn::egui_extras_table_TableRow_col, |mut row: EguiPointer<TableRow<'_, '_>>, callback: EguiCallback| unsafe {
        row.get_mut().col(|ui| {
            callback.invoke(ui as *const _ as *const _);
        })
    })
    // `index` collides with the globally-ignored `Index` trait method name; see `CUSTOM_FNS`
    .with(EguiFn::egui_extras_table_TableRow_index, |row: EguiPointer<TableRow<'_, '_>>| unsafe { row.get().index() })
    // Bindings for TextEdit
    .with(EguiFn::egui_widgets_text_edit_builder_TextEdit_ui, |mut ui: EguiPointer<Ui>, obj: SerializableTextEdit, mut text: String, editable: bool, layouter: Option<EguiCallback>| unsafe {
        let mut layouter_closure = layouter.map(|cb| {
            move |ui: &Ui, buf: &dyn TextBuffer, wrap_width: f32| -> Arc<Galley> {
                let text = buf.as_str();
                let mut out_galley: Option<Galley> = None;
                let params = EguiTextEditLayouterParams {
                    ui: ui as *const _ as usize,
                    text_ptr: text.as_ptr() as usize,
                    text_len: text.len(),
                    wrap_width,
                    out_galley: &mut out_galley as *mut Option<Galley> as usize,
                };
                cb.invoke(&params as *const _ as *const _);
                Arc::new(out_galley.expect("Layouter callback did not produce a Galley"))
            }
        });

        if editable {
            let mut text_edit = obj.to_text_edit(&mut text);
            if let Some(lc) = &mut layouter_closure {
                text_edit = text_edit.layouter(lc);
            }
            (ui.get_mut().add(text_edit), text)
        }
        else {
            let mut text_ref = text.as_str();
            let mut text_edit = obj.to_text_edit(&mut text_ref);
            if let Some(lc) = &mut layouter_closure {
                text_edit = text_edit.layouter(lc);
            }
            (ui.get_mut().add(text_edit), String::default())
        }
    })
    .with(EguiFn::egui_widgets_text_edit_builder_TextEdit_set_galley, |out_galley: usize, galley: Galley| unsafe {
        *(out_galley as *mut Option<Galley>) = Some(galley);
    })
    // `TextEdit::prefix`/`suffix` operate on the real `TextEdit<'a>`, which can't cross the FFI
    // boundary directly (it borrows `text: &'a mut dyn TextBuffer`), so these round-trip through
    // `SerializableTextEdit` and a throwaway text buffer instead of just setting
    // `SerializableTextEdit`'s fields by hand - same reasoning as `Window::drag_area`.
    .with(EguiFn::egui_widgets_text_edit_builder_TextEdit_prefix, |text_edit: SerializableTextEdit, prefix: Atoms| {
        let mut buffer = String::new();
        SerializableTextEdit::from(text_edit.to_text_edit(&mut buffer).prefix(prefix))
    })
    .with(EguiFn::egui_widgets_text_edit_builder_TextEdit_suffix, |text_edit: SerializableTextEdit, suffix: Atoms| {
        let mut buffer = String::new();
        SerializableTextEdit::from(text_edit.to_text_edit(&mut buffer).suffix(suffix))
    })
    // Bindings for Tooltip
    .with(EguiFn::egui_containers_tooltip_Tooltip_show, |ctx: EguiPointer<Context>, popup: SerializablePopup, parent_layer: LayerId, parent_widget: Id, callback: EguiCallback| unsafe {
        (Tooltip {
            popup: popup.to_popup(ctx.get(), &mut true),
            parent_layer,
            parent_widget
        }.show(|ui| callback.invoke(ui as *const _ as *const _)).map(|x| x.response), true)
    })
    // Bindings for Ui
    // `Ui::interact_opt` and `Context::set_cursor_image` are both auto-bound now that
    // `InteractOptions`/`CustomCursorImage` derive serde (added in
    // egui-rs/crates/egui/src/widget_rect.rs and egui-rs/crates/egui/src/data/output.rs).
    .with(EguiFn::egui_ui_Ui_allocate_painter, |mut ui: EguiPointer<Ui>, desired_size: Vec2, sense: Sense| unsafe {
        let (response, painter) = ui.get_mut().allocate_painter(desired_size, sense);
        (response, EguiHandle::to_heap(painter))
    })
    .with(EguiFn::egui_ui_Ui_painter, |ui: EguiPointer<Ui>| unsafe { EguiHandle::to_heap(ui.get().painter().clone()) })
    .with(EguiFn::egui_ui_Ui_painter_at, |ui: EguiPointer<Ui>, rect: Rect| unsafe { EguiHandle::to_heap(ui.get().painter_at(rect)) })
    .with(EguiFn::egui_ui_Ui_next_auto_id, |mut ui: EguiPointer<Ui>| unsafe { (ui.get().next_auto_id() ) })
    .with(EguiFn::egui_ui_Ui_spacing, |ui: EguiPointer<Ui>| unsafe { ui.get().spacing().clone() })
    .with(EguiFn::egui_ui_Ui_style, |ui: EguiPointer<Ui>| unsafe { ui.get().style().clone() })
    .with(EguiFn::egui_ui_Ui_layout, |ui: EguiPointer<Ui>| unsafe { ui.get().layout().clone() })
    .with(EguiFn::egui_ui_Ui_visuals, |ui: EguiPointer<Ui>| unsafe { ui.get().visuals().clone() })
    .with(EguiFn::egui_ui_Ui_visuals_mut, |mut ui: EguiPointer<Ui>, obj: Visuals| unsafe { *ui.get_mut().visuals_mut() = obj })
    .with(EguiFn::egui_ui_Ui_style_mut, |mut ui: EguiPointer<Ui>, obj: Style| unsafe { *ui.get_mut().style_mut() = obj })
    .with(EguiFn::egui_ui_Ui_spacing_mut, |mut ui: EguiPointer<Ui>, obj: Spacing| unsafe { *ui.get_mut().spacing_mut() = obj })
    .with(EguiFn::egui_ui_Ui_stack, |ui: EguiPointer<Ui>| unsafe { ui.get().stack().clone() })
    .with(EguiFn::egui_ui_Ui_separator, |mut ui: EguiPointer<Ui>| unsafe { ui.get_mut().separator() })
    // `Ui::set_enabled` was replaced upstream by the one-way `Ui::disable`; there is no way to
    // re-enable a `Ui` once disabled, so `enabled: true` is a no-op.
    .with(EguiFn::egui_ui_Ui_set_enabled, |mut ui: EguiPointer<Ui>, enabled: bool| unsafe { if !enabled { ui.get_mut().disable(); } })
    .with(EguiFn::egui_ui_Ui_spinner, |mut ui: EguiPointer<Ui>| unsafe { ui.get_mut().spinner() })
    .with(EguiFn::egui_ui_Ui_group, |mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe { ui.get_mut().group(|ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_horizontal, |mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe { ui.get_mut().horizontal(|ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_horizontal_centered, |mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe { ui.get_mut().horizontal_centered(|ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_horizontal_top, |mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe { ui.get_mut().horizontal_top(|ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_horizontal_wrapped, |mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe { ui.get_mut().horizontal_wrapped(|ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_vertical, |mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe { ui.get_mut().vertical(|ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_vertical_centered, |mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe { ui.get_mut().vertical_centered(|ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_vertical_centered_justified, |mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe { ui.get_mut().vertical_centered_justified(|ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_centered_and_justified, |mut ui: EguiPointer<Ui>, callback: EguiCallback| unsafe { ui.get_mut().centered_and_justified(|ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_scope_builder, |mut ui: EguiPointer<Ui>, ui_builder: UiBuilder, callback: EguiCallback| unsafe { ui.get_mut().scope_builder(ui_builder, |ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_indent, |mut ui: EguiPointer<Ui>, id_salt: Id, callback: EguiCallback| unsafe { ui.get_mut().indent(id_salt, |ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_with_visual_transform, |mut ui: EguiPointer<Ui>, transform: TSTransform, callback: EguiCallback| unsafe { ui.get_mut().with_visual_transform(transform, |ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_allocate_ui_with_layout, |mut ui: EguiPointer<Ui>, desired_size: Vec2, layout: Layout, callback: EguiCallback| unsafe { ui.get_mut().allocate_ui_with_layout(desired_size, layout, |ui| callback.invoke(ui as *const _ as *const _)).response })
    .with(EguiFn::egui_ui_Ui_columns, |mut ui: EguiPointer<Ui>, num_columns: usize, callback: EguiCallback| unsafe {
        ui.get_mut().columns(num_columns, |ui_list| callback.invoke(ui_list.iter_mut().map(|x| x as *const _ as *const _).collect::<Vec<*const c_void>>().as_ptr() as *const _))
    })
    .with(EguiFn::egui_ui_Ui_place, |mut ui: EguiPointer<Ui>, max_rect: Rect, callback: EguiCallback| unsafe {
        ui.get_mut().place(max_rect, |ui: &mut Ui| { callback.invoke(ui as *const _ as *const _); ui.response() })
    })
    // Bindings for WidgetText
    .with(EguiFn::egui_widget_text_WidgetText_text, |x: WidgetText| x.text().to_string())
    // Bindings for ViewportId
    // `from_hash_of` takes `impl AsId` (a blanket trait for `Hash + Debug`), which the autobinder
    // can't handle generically; bound concretely against `String`, matching `Id::new`/`Id::with`.
    .with(EguiFn::egui_viewport_ViewportId_from_hash_of, |source: String| ViewportId::from_hash_of(source))
    // Bindings for Window
    .with(EguiFn::egui_containers_window_Window_show, |ctx: EguiPointer<Context>, window: SerializableWindow, open: Option<bool>, add_contents: EguiCallback| unsafe {
        let window = Window::from(window);
        if let Some(mut is_open) = open {
            let response = window.open(&mut is_open).show(ctx.get(), |ui| add_contents.invoke(ui as *const _ as *const _));
            (response.map(|x| x.response), is_open)
        }
        else {
            let response = window.show(ctx.get(), |ui| add_contents.invoke(ui as *const _ as *const _));
            (response.map(|x| x.response), true)
        }
    })
    // `Window::drag_area`/`from_viewport` operate on the real `Window<'a>`, which can't cross
    // the FFI boundary directly (it borrows `open: Option<&'a mut bool>`), so these round-trip
    // through `SerializableWindow` instead of just setting `SerializableWindow`'s fields by hand.
    .with(EguiFn::egui_containers_window_Window_drag_area, |window: SerializableWindow, drag_area: WindowDrag| {
        SerializableWindow::from(Window::from(window).drag_area(drag_area))
    })
    .with(EguiFn::egui_containers_window_Window_from_viewport, |id: ViewportId, viewport: ViewportBuilder| {
        SerializableWindow::from(Window::from_viewport(id, viewport))
    })
    // Miscellaneous
    .with(EguiFn::emath_format_with_decimals_in_range, format_with_decimals_in_range as fn(f64, RangeInclusive<usize>) -> _);

/// Callback data for a UI and time.
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EguiAnimatedUi {
    /// A pointer to the UI.
    pub ui: usize,
    /// The animation time.
    pub t: f32
}

/// Callback data for [`Panel::show_switched`].
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EguiSwitchedUi {
    /// A pointer to the UI.
    pub ui: usize,
    /// Whether the expanded (`true`) or collapsed (`false`) panel is being shown.
    pub expanded: bool
}

impl EguiAnimatedUi {
    /// Creates a new animated UI instance.
    pub fn new(ui: &mut Ui, t: f32) -> Self {
        Self {
            ui: ui as *const _ as usize,
            t
        }
    }
}

/// A C# callback for `egui` to invoke.
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EguiCallback {
    /// The function to call.
    func: unsafe extern "C" fn(*const c_void, *const c_void),
    /// Data to pass as the second function argument.
    data: *const c_void
}

unsafe impl Send for EguiCallback {}
unsafe impl Sync for EguiCallback {}

impl EguiCallback {
    /// Invokes the callback.
    /// 
    /// # Safety
    /// 
    /// All invariants for [`Self::func`] must be satisfied.
    pub unsafe fn invoke(&self, argument: *const c_void) {
        (self.func)(argument, self.data)
    }
}

impl Serialize for EguiCallback {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: Serializer {
        [self.func as usize, self.data as usize].serialize(serializer)
    }
}

impl<'a> Deserialize<'a> for EguiCallback {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where
            D: Deserializer<'a> {
        unsafe {
            let [func, data] = <[usize; 2] as Deserialize<'a>>::deserialize(deserializer)?;
            Ok(Self {
                func: transmute(func),
                data: data as *const _
            })
        }
    }
}

/// An `egui` object that is passed by reference.
#[derive(Copy, Clone, Serialize, Deserialize)]
#[repr(C)]
pub struct EguiPointer<T> {
    /// The underlying pointer.
    ptr: usize,
    /// Marker data identifying the type.
    marker: PhantomData<*mut T>
}

impl<T> EguiPointer<T> {
    /// Gets a reference to the underlying object.
    /// 
    /// # Safety
    /// 
    /// The pointer must be valid, and no mutable references may exist to it.
    pub unsafe fn get(&self) -> &T {
        assert_ne!(self.ptr, 0, "egui object was not initialized");
        &*(self.ptr as *const _)
    }

    /// Gets a mutable reference to the underlying object.
    ///
    /// # Safety
    ///
    /// The pointer must be valid, and no other references may exist to it.
    pub unsafe fn get_mut(&mut self) -> &mut T {
        assert_ne!(self.ptr, 0, "egui object was not initialized");
        &mut *(self.ptr as *mut _)
    }
}

/// Represents a heap-allocated `egui` object.
#[derive(Copy, Clone, Serialize, Deserialize)]
#[repr(C)]
pub struct EguiHandle {
    /// A pointer to the object.
    ptr: usize,
    /// Metadata about the pointer used for internal purposes.
    metadata: usize
}

impl EguiHandle {
    /// Allocates `value` on the heap and returns a handle to it.
    pub fn to_heap<T: 'static>(value: T) -> Self {
        let ptr = Box::into_raw(Box::new(value)) as _;
        let metadata = Self::drop::<T> as _;
        Self {
            ptr,
            metadata
        }
    }

    /// Destroys the instance of `T` at `ptr` and frees the memory.
    /// 
    /// # Safety
    /// 
    /// `ptr` must refer to a valid instance of type `T` created
    /// with [`Self::to_heap`].
    unsafe fn drop<T: 'static>(ptr: *mut T) {
        Box::from_raw(ptr);
    }
}

/// Describes the result of an `egui` call.
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EguiInvokeResult {
    /// Whether `return_value` holds a serialized value or an error string.
    pub success: bool,
    /// If [`Self::success`], then the serialized data that the function returned.
    /// Otherwise, holds a UTF8 string describing what went wrong.
    pub return_value: EguiSliceU8
}

/// Describes a section of a `u8` array.
#[derive(Copy, Clone)]
#[repr(C)]
pub struct EguiSliceU8 {
    /// A pointer to the data buffer.
    pub ptr: *const u8,
    /// The length of the data in bytes.
    pub len: usize
}

impl EguiSliceU8 {
    /// Converts `x` to an FFI-compatible slice.
    /// 
    /// # Safety
    /// 
    /// The lifetime of the returned slice should not outlive `x`. 
    pub const fn from_slice(x: &[u8]) -> Self {
        Self {
            ptr: x.as_ptr(),
            len: x.len()
        }
    }

    /// Converts this object to a Rust slice pointer.
    /// 
    /// # Safety
    /// 
    /// For this function call to be sound, `self` must refer
    /// to a valid array of `u8` with at least [`Self::len`] elements.
    pub unsafe fn to_ptr(&self) -> *const [u8] {
        if self.len == 0 {
            &[]
        }
        else {
            std::slice::from_raw_parts(self.ptr, self.len)
        }
    }

    /// Converts this object to a Rust slice.
    /// 
    /// # Safety
    /// 
    /// For this function call to be sound, `self` must refer
    /// to a valid array of `u8` with at least [`Self::len`] elements.
    pub unsafe fn to_slice(&self) -> &[u8] {
        if self.len == 0 {
            &[]
        }
        else {
            std::slice::from_raw_parts(self.ptr, self.len)
        }
    }
}

/// Initializes the `egui` bindings library.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn egui_init() {
    panic::set_hook(Box::new(|_| ()));
}

/// Invokes a bound `egui` function.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn egui_invoke(f: EguiFn, args: EguiSliceU8) -> EguiInvokeResult {
    /// The serialization buffer to which results will be written.
    ///
    /// Plain `static mut` on wasm32: real `#[thread_local]` storage needs the embedder to call
    /// Rust's `__wasm_init_tls` per instance to set up `__tls_base`, which the .NET wasm runtime
    /// has no reason to know about when this crate is just a statically-linked archive; without
    /// it, any TLS access traps ("memory access out of bounds") on an uninitialized base pointer.
    /// This is sound here because the target is embedded single-threaded (Mono's WASM runtime).
    #[cfg(not(target_arch = "wasm32"))]
    #[thread_local]
    static mut RETURN_BUFFER: Vec<u8> = Vec::new();
    #[cfg(target_arch = "wasm32")]
    static mut RETURN_BUFFER: Vec<u8> = Vec::new();

    match catch_unwind(|| {
        if let Some(invoker) = EGUI_FNS.inner[f as usize] {
            invoker.invoke(f, args.to_ptr(), std::ptr::addr_of_mut!(RETURN_BUFFER));
            EguiInvokeResult {
                success: true,
                return_value: EguiSliceU8::from_slice(&*std::ptr::addr_of_mut!(RETURN_BUFFER))
            }
        }
        else {
            panic!("Function {f:?} not implemented")
        }
    }) {
        Ok(x) => x,
        Err(error) => {
            let error_message = error.downcast_ref::<&'static str>()
                .map(|x| x.to_string())
                .unwrap_or_else(|| error.downcast_ref::<String>().cloned().unwrap_or_default());
            
            let return_buffer = &mut *std::ptr::addr_of_mut!(RETURN_BUFFER);
            return_buffer.clear();
            for character in error_message.encode_utf16() {
                return_buffer.extend(character.to_ne_bytes());
            }

            EguiInvokeResult {
                success: false,
                return_value: EguiSliceU8::from_slice(&return_buffer)
            }
        }
    }
}

/// Frees an `egui` object from the heap.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn egui_drop(handle: EguiHandle) {
    transmute::<usize, unsafe fn(usize)>(handle.metadata)(handle.ptr)
}

/// Holds bindings for all `egui` functions and allows for translating from [`EguiFn`] names to function pointers.
struct EguiFnMap {
    /// A mapping from [`EguiFn`] bindings to the underlying function to invoke.
    inner: [Option<EguiFnInvoker>; EguiFn::ALL.len()]
}

impl EguiFnMap {
    /// Adds a function (that has call-by-value semantics) and returns the new map.
    pub const fn with<A: DeserializeOwned + Tuple, R: Serialize>(mut self, binding: EguiFn, f: impl Copy + Fn<A, Output = R>) -> Self {
        self.inner[binding as usize] = Some(EguiFnInvoker::new(f));
        self
    }
}

/// Creates a new, empty function map.
const fn egui_fn_map() -> EguiFnMap {
    EguiFnMap {
        inner: [None; EguiFn::ALL.len()]
    }
}

/// A type-erased `egui` function that may be called with serialized arguments/result.
#[derive(Copy, Clone, Debug)]
struct EguiFnInvoker {
    /// The `fn` object to pass to `func`.
    data: *const (),
    /// The [`EguiFnInvokable::invoke`] method to call.
    func: unsafe fn(EguiFn, *const (), *const [u8], *mut Vec<u8>)
}

impl EguiFnInvoker {
    /// Stores the provided [`EguiFnInvokable`] on the stack for later use.
    /// `F` should be a `fn` pointer.
    pub const fn new<A: DeserializeOwned + Tuple, F: Copy + Fn<A, Output: Serialize>>(f: F) -> Self {
        unsafe {
            /// Allows for safely reading the data of `f`.
            #[repr(C)]
            struct PaddedPtr<F> {
                /// The function being called.
                pub f: F,
                /// Padding for when `F` is less than the size of a pointer.
                pub padding: *const ()
            }

            if size_of::<*const ()>() < size_of::<F>() || align_of::<*const ()>() < align_of::<F>() {
                panic!("Invokable function must be thin pointer");
            }

            let padded = PaddedPtr { f, padding: std::ptr::null() };

            Self {
                data: std::ptr::read(&padded as *const _ as *const _),
                func: transmute(Self::call_fn::<A, F> as unsafe fn(_, _, _, _))
            }
        }
    }

    /// Invokes the underlying function.
    /// 
    /// # Safety
    /// 
    /// For this function call to be sound, `ptr` must refer to a valid instance
    /// of the invoker function's type. 
    pub unsafe fn invoke(&self, fn_id: EguiFn, args: *const [u8], ret: *mut Vec<u8>) {
        (self.func)(fn_id, &self.data as *const _ as *const _, args, ret)
    }

    /// Invokes the underlying function.
    /// 
    /// # Safety
    /// 
    /// For this function call to be sound, `ptr` must refer to a valid instance
    /// of the invoker function's type. 
    unsafe fn call_fn<A: DeserializeOwned + Tuple, F: Copy + Fn<A, Output: Serialize>>(fn_id: EguiFn, f: &F, args: *const [u8], ret: *mut Vec<u8>) {
        let deserialized_args = bincode::deserialize(&*args)
            .unwrap_or_else(|_| panic!("Failed to decode args for call {fn_id:?}"));
        let result = f.call(deserialized_args);
        (*ret).clear();
        bincode::serialize_into(&mut *ret, &result)
            .unwrap_or_else(|_| panic!("Failed to encode result for call {fn_id:?}"));
    }
}

/// Params for `egui_context_Context_run_tessellate`.
#[repr(C)]
pub struct EguiContextRunTessellateParams {
    /// The context pointer.
    pub ctx: usize,
    /// A pointer to the serialized input.
    pub raw_input: *const u8,
    /// The length of the serialized input.
    pub raw_input_len: usize,
    /// The callback to invoke.
    pub callback: EguiCallback
}

/// Parameters for [`ScrollArea::show_rows`].
#[repr(C)]
pub struct EguiScrollAreaShowRowsParams {
    pub ui: usize,
    pub start: usize,
    pub end: usize
}

/// Parameters for [`ScrollArea::show_viewport`].
#[repr(C)]
pub struct EguiScrollAreaShowViewportParams {
    pub ui: usize,
    pub min_x: f32,
    pub min_y: f32,
    pub max_x: f32,
    pub max_y: f32,
}

/// Parameters for a [`TextEdit`] layouter callback.
#[repr(C)]
pub struct EguiTextEditLayouterParams {
    pub ui: usize,
    pub text_ptr: usize,
    pub text_len: usize,
    pub wrap_width: f32,
    pub out_galley: usize,
}

/// Parameters for [`CollapsingState::show_toggle_button`].
struct EguiCollapsingStateShowToggleButtonParams<'a> {
    pub ui: &'a mut Ui,
    pub openness: f32,
    pub response: &'a Response
}

/// Helper struct for serializing popups
#[derive(Clone, Serialize, Deserialize)]
struct SerializablePopup {
    pub id: Id,
    pub anchor: PopupAnchor,
    pub rect_align: RectAlign,
    pub alternative_aligns: Option<Vec<RectAlign>>,
    pub layer_id: LayerId,
    pub open_kind: u8,
    pub open_command: Option<SetOpenCommand>,
    pub close_behavior: PopupCloseBehavior,
    pub info: Option<UiStackInfo>,
    pub kind: PopupKind,
    pub gap: f32,
    pub width: Option<f32>,
    pub sense: Sense,
    pub layout: Layout,
    pub frame: Option<Frame>,
    pub style: Option<Style>,
    pub menu_style: bool
}

impl SerializablePopup {
    pub fn to_popup<'a>(&'a self, ctx: &Context, open_bool: &'a mut bool) -> Popup<'a> {
        Popup {
            id: self.id,
            open_kind: match self.open_kind {
                0 => OpenKind::Open,
                1 => OpenKind::Closed,
                2 => OpenKind::Bool(open_bool),
                3 => OpenKind::Memory { set: self.open_command.clone() },
                _ => panic!("Invalid open kind value")
            },
            ctx: ctx.clone(),
            anchor: self.anchor,
            rect_align: self.rect_align,
            alternative_aligns: self.alternative_aligns.as_deref(),
            layer_id: self.layer_id,
            close_behavior: self.close_behavior,
            info: self.info.clone(),
            kind: self.kind,
            gap: self.gap,
            width: self.width,
            sense: self.sense,
            layout: self.layout,
            frame: self.frame,
            style: if self.menu_style {
                StyleModifier::from(menu_style)
            } else if let Some(style) = &self.style {
                style.clone().into()
            }
            else {
                StyleModifier::default()
            },
        }
    }
}

/// Helper struct for serializing windows
#[derive(Clone, Serialize, Deserialize)]
struct SerializableWindow {
    title: Atoms,
    area: Area,
    frame: Option<Frame>,
    resize: Resize,
    scroll: ScrollArea,
    collapsible: bool,
    default_open: bool,
    with_title_bar: bool,
    fade_out: bool,
    auto_sized: bool,
    drag_area: WindowDrag,
}

impl<'a> From<SerializableWindow> for Window<'a> {
    fn from(value: SerializableWindow) -> Self {
        Window {
            title: value.title,
            open: None,
            area: value.area,
            frame: value.frame,
            resize: value.resize,
            scroll: value.scroll,
            collapsible: value.collapsible,
            default_open: value.default_open,
            with_title_bar: value.with_title_bar,
            fade_out: value.fade_out,
            auto_sized: value.auto_sized,
            drag_area: value.drag_area,
        }
    }
}

impl From<Window<'_>> for SerializableWindow {
    // `open` is dropped: this conversion is only ever used for builder-chain methods that run
    // before `.Open()`/`.Show()` are called from C#, at which point the wire-level window never
    // carries an `open` reference (that's threaded through separately, as a `ref bool` argument
    // to `Window::Show`).
    fn from(value: Window<'_>) -> Self {
        SerializableWindow {
            title: value.title,
            area: value.area,
            frame: value.frame,
            resize: value.resize,
            scroll: value.scroll,
            collapsible: value.collapsible,
            default_open: value.default_open,
            with_title_bar: value.with_title_bar,
            fade_out: value.fade_out,
            auto_sized: value.auto_sized,
            drag_area: value.drag_area,
        }
    }
}

#[derive(Serialize, Deserialize)]
struct SerializableTextEdit {
    pub hint_text: Atoms,
    pub prefix: Atoms,
    pub suffix: Atoms,
    pub id: Option<Id>,
    pub id_salt: Option<IdSalt>,
    pub font_selection: FontSelection,
    pub text_color: Option<Color32>,
    pub password: bool,
    pub frame: Option<Frame>,
    pub margin: Margin,
    pub multiline: bool,
    pub interactive: bool,
    pub desired_width: Option<f32>,
    pub desired_height_rows: usize,
    pub event_filter: EventFilter,
    pub cursor_at_end: bool,
    pub min_size: Vec2,
    pub align: Align2,
    pub clip_text: bool,
    pub char_limit: usize,
    pub return_key: Option<KeyboardShortcut>,
    pub background_color: Option<Color32>,
}

impl SerializableTextEdit {
    /// Converts this to a usable [`TextEdit`] widget.
    pub fn to_text_edit<'a>(self, text: &'a mut impl TextBuffer) -> TextEdit {
        TextEdit {
            text,
            hint_text: self.hint_text,
            prefix: self.prefix,
            suffix: self.suffix,
            id: self.id,
            id_salt: self.id_salt,
            font_selection: self.font_selection,
            text_color: self.text_color,
            password: self.password,
            frame: self.frame,
            layouter: None,
            margin: self.margin,
            multiline: self.multiline,
            interactive: self.interactive,
            desired_width: self.desired_width,
            desired_height_rows: self.desired_height_rows,
            event_filter: self.event_filter,
            cursor_at_end: self.cursor_at_end,
            min_size: self.min_size,
            align: self.align,
            clip_text: self.clip_text,
            char_limit: self.char_limit,
            return_key: self.return_key,
            background_color: self.background_color,
        }
    }
}

impl From<TextEdit<'_>> for SerializableTextEdit {
    // `text`/`layouter` are dropped: this conversion is only used for builder-chain methods that
    // run before the real text buffer is known, at which point the wire-level text edit never
    // carries one (or a custom layouter) - `to_text_edit` always passes a throwaway buffer and
    // `layouter: None` for exactly this reason.
    fn from(value: TextEdit<'_>) -> Self {
        SerializableTextEdit {
            hint_text: value.hint_text,
            prefix: value.prefix,
            suffix: value.suffix,
            id: value.id,
            id_salt: value.id_salt,
            font_selection: value.font_selection,
            text_color: value.text_color,
            password: value.password,
            frame: value.frame,
            margin: value.margin,
            multiline: value.multiline,
            interactive: value.interactive,
            desired_width: value.desired_width,
            desired_height_rows: value.desired_height_rows,
            event_filter: value.event_filter,
            cursor_at_end: value.cursor_at_end,
            min_size: value.min_size,
            align: value.align,
            clip_text: value.clip_text,
            char_limit: value.char_limit,
            return_key: value.return_key,
            background_color: value.background_color,
        }
    }
}

#[derive(Clone, Serialize, Deserialize)]
pub struct SerializableTableBuilder {
    id_salt: Option<String>,
    columns: Vec<Column>,
    striped: Option<bool>,
    cell_layout: Option<Layout>,
    resizable: bool,
    sense: Sense,
    vscroll: bool,
    drag_to_scroll: DragScroll,
    stick_to_bottom: bool,
    scroll_to_row: Option<(usize, Option<Align>)>,
    vertical_scroll_offset: Option<f32>,
    min_scrolled_height: f32,
    max_scroll_height: f32,
    auto_shrink: Vec2b,
    scroll_bar_visibility: ScrollBarVisibility,
    animate_scrolling: bool
}

#[derive(Clone, Serialize, Deserialize)]
pub struct SerializableStripBuilder {
    clip: bool,
    cell_layout: Option<Layout>,
    sense: Sense,
    sizes: Vec<Size>
}

#[derive(Clone, Serialize, Deserialize)]
pub struct SerializableDatePickerButton {
    id_salt: Option<String>,
    combo_boxes: bool,
    arrows: bool,
    calendar: bool,
    calendar_week: bool,
    show_icon: bool,
    format: String,
    highlight_weekends: bool,
    start_end_years: Option<(i16, i16)>,
    reverse_years: bool,
    year_scroll_to: Option<i16>
}

#[derive(Clone, Serialize, Deserialize)]
pub struct SerializableDragValue {
    speed: f64,
    prefix: Atoms,
    suffix: Atoms,
    start: f64,
    end: f64,
    clamp_existing_to_range: bool,
    min_decimals: usize,
    max_decimals: Option<usize>,
    update_while_editing: bool,
    min_width: usize,
    twos_complement: bool,
    upper: bool,
    parser: u8
}

impl SerializableDragValue {
    /// Converts this to a usable [`DragValue`] widget.
    pub fn to_drag_value<'a>(self, value: &'a mut f64) -> DragValue<'a> {
        let mut result = DragValue::new(value)
            .speed(self.speed)
            .prefix(self.prefix)
            .suffix(self.suffix)
            .range(self.start..=self.end)
            .clamp_existing_to_range(self.clamp_existing_to_range)
            .min_decimals(self.min_decimals)
            .max_decimals_opt(self.max_decimals)
            .update_while_editing(self.update_while_editing);

        match self.parser {
            0 => result,
            2 => result.binary(self.min_width, self.twos_complement),
            8 => result.octal(self.min_width, self.twos_complement),
            16 => result.hexadecimal(self.min_width, self.twos_complement, self.upper),
            _ => panic!("Unrecognized DragValue parser type")
        }
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct SerializableSlider {
    pub start: f64,
    pub end: f64,
    pub spec: SliderSpec,
    pub clamping: SliderClamping,
    pub smart_aim: bool,
    pub show_value: bool,
    pub orientation: SliderOrientation,
    pub prefix: String,
    pub suffix: String,
    pub text: WidgetText,
    pub step: Option<f64>,
    pub drag_value_speed: Option<f64>,
    pub min_decimals: usize,
    pub max_decimals: Option<usize>,
    pub trailing_fill: Option<bool>,
    pub handle_shape: Option<HandleShape>,
    pub update_while_editing: bool,
    pub min_width: usize,
    pub twos_complement: bool,
    pub upper: bool,
    pub parser: u8,
}

impl SerializableSlider {
    /// Converts this to a usable [`Slider`] widget.
    pub fn to_slider<'a>(self, value: &'a mut f64) -> Slider<'a> {
        let mut result = Slider {
            spec: self.spec,
            clamping: self.clamping,
            smart_aim: self.smart_aim,
            show_value: self.show_value,
            orientation: self.orientation,
            prefix: self.prefix,
            suffix: self.suffix,
            text: self.text,
            step: self.step,
            drag_value_speed: self.drag_value_speed,
            min_decimals: self.min_decimals,
            max_decimals: self.max_decimals,
            trailing_fill: self.trailing_fill,
            handle_shape: self.handle_shape,
            update_while_editing: self.update_while_editing,
            ..Slider::new(value, self.start..=self.end)
        };

        match self.parser {
            0 => result,
            2 => result.binary(self.min_width, self.twos_complement),
            8 => result.octal(self.min_width, self.twos_complement),
            16 => result.hexadecimal(self.min_width, self.twos_complement, self.upper),
            _ => panic!("Unrecognized DragValue parser type")
        }
    }
}

/// Functions that can be run as tests.
#[cfg(test)]
mod tests {
    use super::*;
    
    /// Creates a list of all unbound methods and stubs for them. 
    #[test]
    fn report_unbound_methods() {
        let mut result = String::new();
        let mut bound = 0;

        for func in EguiFn::ALL {
            if EGUI_FNS.inner[*func as usize].is_none() {
                result += &format!("{func:?}\n");
            }
            else {
                bound += 1;
            }
        }

        result = format!("{bound} / {} ({}%) bound\n{result}", EguiFn::ALL.len(), (100.0 * bound as f32 / EguiFn::ALL.len() as f32).floor());
        std::fs::write("progress_report.txt", result).expect("Failed to write progress report");
    }
}