[build]
rustflags = [
    "-Z", "share-generics=y",
    "-Z", "threads=8"
]

[target.wasm32-unknown-unknown]
rustflags = [
    "-Z", "share-generics=y",
    "-Z", "threads=8",
    "-C", "panic=unwind"
]
