name: Pack

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dsherret/rust-toolchain-file@v1

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Install from git rather than the last crates.io release, since the
      # release predates `workspace.metadata.cross` support in Cargo.toml.
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross --locked

      - name: Pack
        run: dotnet pack Egui.NET.slnf -c Release --output nupkgs

      - name: Upload nupkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: nupkgs/*.nupkg
